### ISSUE TITLE
Store Documents in (Vector) Database

### ISSUE THREAD

**Issue by carschno** [Semantics-of-Sustainability/tempo-embeddings#32]
Current Situation
=============
All documents are stored in memory in the `Passage` objects, including text, metadata, and embedding vectors. This does not scale beyond the local machine's memory. Furthermore, embeddings are not stored persistently and need to be re-computed if the local process is terminated. 

Solution
=============
Documents should be stored in a suitable database so that they can be stored persistently on disk and retrieved when necessary.

Discussion
=============
There are specific vector databases such as [Weaviate](https://weaviate.io/). To be investigated: is a vector database really necessary? Perhaps a SQL or a NoSQL database are alternatives. Weaviate might have the advantage with its off-the-shelve support for generating embeddings from Transformer models (see [documentation](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-transformers#option-3-a-private-or-local-model)).

Steps
=============
- [x] Investigate suitable database solutions
- [x] Implement API to database for storing and retrieving documents and embeddings
- [ ] Extend `Passage` class so that passages read from any format (such as the existing CSVs) and stored in the database
- [x] Extend architecture so that `Passage` objects are read from the database

**Comment by angel-daza** [comment]
After some research, The three most interesting open source Vecor DBs are:
* [Chroma](https://docs.trychroma.com/)
* [Qdrant](https://github.com/qdrant/qdrant-client)
* [ElasticSearch Vector DB](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/semantic-search.html)

Since the idea is anyway to create a wrapper that works with different DB engines, I chose to use *Chroma* as the first implementation because it has the most lightweight API and complies with the most important characteristics that we care about for now:
* Works with all HuggingFace models, Cohere, or even ad-hoc embedding functions among others.
* Can be queried by Metadata, partial string matching on the original text or Vector neighborhoods close to a given string query.
* Can use different distance metrics to calculate vector neighborhoods

**Comment by carschno** [comment]
Nice overview, thanks!
Just out of curiosity: it looks like ElasticSearch seems to provide the three most important criteria you mention, too.

I am not particularly in favour of ES over the others, except that I personally have more experience with it.  Anyway, given the architecture that we discussed, can still try alternative backends later, so do not let this question block you!

**Comment by angel-daza** [comment]
As a starter, Chroma is nice because it uses SQLite in the background, so it is easy to share the database by just sharing the sqlite file. I've finished the API class and now will work on integrating it with the `Model` and `Passage` classes.

**Comment by carschno** [comment]
Just for future reference: there is an [open-source version of the Weaviate database](https://github.com/weaviate/weaviate).
